name: flutter_hooks_sample
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  shared_preferences: ^0.5.7+3

  provider: ^4.1.3
  state_notifier: ^0.5.0
  flutter_state_notifier: ^0.4.2
  flutter_hooks: ^0.9.0
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.9.1
  build_runner: ^1.10.0
  freezed: ^0.10.9

flutter:
  uses-material-design: true
